### ISSUE TITLE
Configurar CI

### ISSUE THREAD

**Issue by gliborgmx** [gliborgmx/static-glib#1]
Cuando se hace un PR a main:

+ [x] Revisar ortografía del nuevo artículo (aspell)
+ [x] Revisar formato ([pymarkdownlint](https://pypi.org/project/pymarkdownlint/)) 
+ ~[ ] Revistar imágenes (JPEG sof 0, chroma 4:2:0)~
+ [x] Generar correctamente el sitio estático con Zola

Cuando se hace merge a main:

+ [x] Generar el sitio estático con Zola
+ [x] Rsync al servidor (usar una cuenta con  [rush](https://www.gnu.org.ua/software/rush/))

**Comment by ceyusa** [comment]
Ya comencé esta tarea.

**Comment by ceyusa** [comment]
Tarea completada. He borrado la revisión de las imágenes porque no es tan simple como imaginé: todo indica que hay que desarrollar una herramienta específica, porque no encontré ninguna.

Estoy muy contento.
